spring:
  application:
    name: torrefactora
  profiles:
    active: dev
---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        hbm2ddl:
          auto: create
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:/sql/data.sql
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/torrefactora?createDatabaseIfNotExist=true
    username: root
    password:
  jackson:
    time-zone: America/Bogota